IsEmpty = 0
Count   = 8
First   = Mercury
Last    = Neptune
Contains(Pluto) = 0
Contains(Earth) = 1
First Removed   = Mercury
First   = Venus
Last Removed    = Neptune
Last    = Uranus
Count   = 6
ValueAtIndex(2) = Mars
